services:
  # Source Kafka Cluster
  kafka-source:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka-source
    container_name: kafka-source
    ports:
      - "9092:9092"
      - "19092:19092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-source:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-source:29092,CONTROLLER://kafka-source:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-source:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    volumes:
      - kafka-source-data:/var/lib/kafka/data
    networks:
      - kafka

  # Source Redpanda Console
  console-source:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: console-source
    ports:
      - "8180:8080"
    environment:
      KAFKA_BROKERS: kafka-source:29092
    depends_on:
      - kafka-source
    networks:
      - kafka

  # Target Kafka Cluster
  kafka-target:
    image: confluentinc/cp-kafka:7.6.0
    hostname: kafka-target
    container_name: kafka-target
    ports:
      - "9093:9093"
      - "19093:19093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka-target:29092,PLAINTEXT_HOST://localhost:9093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka-target:29092,CONTROLLER://kafka-target:29093,PLAINTEXT_HOST://0.0.0.0:9093'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka-target:29093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Ql'
    volumes:
      - kafka-target-data:/var/lib/kafka/data
    networks:
      - kafka

  # Target Redpanda Console
  console-target:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: console-target
    ports:
      - "8181:8080"
    environment:
      KAFKA_BROKERS: kafka-target:29092
    depends_on:
      - kafka-target
    networks:
      - kafka

networks:
  kafka:
    driver: bridge
    name: kafka

volumes:
  kafka-source-data:
  kafka-target-data:
