kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      # Kannika Console
      - containerPort: 30080
        hostPort: 8080
        protocol: TCP
      # Kannika API
      - containerPort: 30081
        hostPort: 8081
        protocol: TCP
