# AWS Credentials for MinIO access
apiVersion: kannika.io/v1alpha
kind: Credentials
metadata:
  name: s3-minio-creds
  namespace: kannika-data
spec:
  aws:
    accessKeyIdFrom:
      secretKeyRef:
        name: s3-minio-creds
        key: accessKeyId
    secretAccessKeyFrom:
      secretKeyRef:
        name: s3-minio-creds
        key: secretAccessKey
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: s3-minio-creds
  namespace: kannika-data
data:
  accessKeyId: bWluaW9hZG1pbg==         # minioadmin
  secretAccessKey: bWluaW9hZG1pbg==     # minioadmin
